### ISSUE TITLE
Importer le projet sur gitlab

### ISSUE THREAD

**Issue by moussadiallo** [sokhnaawa19/sokhnaawa19#1]
Projet très interessant surtout la partie "échange de livres", wiki bien documenté c'est bien.
Maintenant il faut importer le projet sur gitlab et créer un autre repository sur gitlab ou vous allez pusher votre template.
Faites tout pour que ça aboutisse, c'est un bon projet.

**Comment by sokhnaawa19** [comment]
Merci. on déploiera le projet sur gitlab dès que possible.
Sinon on voudrai savoir si c'est obligatoire ou nécessaire de mettre les
mêmes informations (photos descriptions etc.....)  sur nos wikis respectifs?

2018-01-27 14:19 GMT+00:00 moussa diallo <notifications@github.com>:

**Comment by moussadiallo** [comment]
Je vous fait faire les wikis github pour votre vie professionelle future, cela vous aidera à montrer ce que vous savez faire donc mieux vaut documenter vos wikis personnels. Pour ce qui est du code qui sera sur gitlab vous pouvez partager votre repo.
PS: une fois le travail fait n'oubliez pas de fermer l'issue pour que je vérifie.
